language: java
jdk: oraclejdk8
sudo: false

# unit test
#script: "mvn -B -P indy clean test"

# integration test
before_install: "mvn -B clean"
install: "mvn -B -P indy install"
before_script: "mvn -B invoker:install"
script: "mvn -B -P indy -Dinvoker.streamLogs=true invoker:run"
